### PR TITLE
document use as Visual Studio test adapter

### PR DESCRIPTION
**Pull request by jackfoxy**
All credit to @slang25 
I'm just documenting what he told me.

### CODE REVIEW

**Comment by Alxandr** [comment]
Thanks a lot. Would you mind adding the same entires for non-paket users? Basically, the same packages, but `<PackageReference>`s?

**Comment by jackfoxy** [comment]
I can make something up, but I don't know what I'm doing in a non-paket environment because I always use paket.

**Comment by jackfoxy** [comment]
I added a line about ```<PackageReference>```s

**Comment by Alxandr** [comment]
I made some modifications to the readme you provided. It should still contain the information required by consumers of the library. I also moved it up to a more prevalent place in the readme. Thanks for your contribution :).

**Pull request merged**
