### PR TITLE
Add ability to run only specific tests

### LINKED ISSUE #16: 'executor://yolodev/expecto': Not implemented
Hi, I'm having some issues running my expecto tests using this library.

The tests are discovered and appear in the test explorer, but whenever I select and run a test I get this executor error:

```
[16/10/2018 1:39:54 PM Informational] ------ Run test started ------
[16/10/2018 1:39:59 PM Error] An exception occurred while invoking executor 'executor://yolodev/expecto': Not implemented (run testcases)
[16/10/2018 1:40:00 PM Informational] ========== Run test finished: 0 run (0:00:05.6159986) ==========
```

I'm running
- Visual Studio 2017: 15.8.3
- YoloDev.Expecto.TestSdk: 0.5.0
- .Net Core: 2.1
- F# Core: 4.5.2
- Expecto: 8.4.2

FYI: I did have to change the test projects from executable to library for the tests to be discovered.

### PR DESCRIPTION
**Pull request by Alxandr**
This is untested, and I don't know how to test it.

Resolves #16

### CODE REVIEW

**Comment by slang25** [comment]
I'll test this tonight 👍

**Comment by slang25** [comment]
This worked great @Alxandr, I ran a single test against master and got an exception, then checkout out this branch and it works!
image

**Comment by slang25** [comment]
I found this impossible to test on a mac btw, doesn't seem to be an easy way to host the test adapter in such a way to hit that method.

**Comment by Alxandr** [comment]
Can you add side effect to the tests (write to a file or such) to see if it's really just running the requested ones?

**Comment by slang25** [comment]
Good idea. I've done as you've suggested and have a test that creates a file in the current directory.
Running all tests creates the file, after clearing out the file and running just `test1` it doesn't create the file 🎉

**Comment by Alxandr** [comment]
Prefect. Thanks for the help. Will release the new version.

**Comment by slang25** [comment]
@Alxandr Any progress on the new release? I'd love to share this with my workmates.

**Comment by Alxandr** [comment]
Ah. I was mixing up projects. I thought this one released automatically. I've started the release process.

**Comment by slang25** [comment]
Brilliant 😃 Thanks again @Alxandr

**Pull request merged**
