### PR TITLE
Add lib folder dummies for net461to fix pack step errors.

### PR DESCRIPTION
**Pull request by gdziadkiewicz**
Tagged as v0.9.42 and build in https://github.com/gdziadkiewicz/YoloDev.Expecto.TestSdk/runs/732713773?check_suite_focus=true

### CODE REVIEW

**Comment by gdziadkiewicz** [comment]
To test the whole process I created MyGet account for myself, did the necessary config changes and managed to get a build on the master branch that looks like that https://github.com/gdziadkiewicz/YoloDev.Expecto.TestSdk/runs/732788236?check_suite_focus=true and results in https://www.myget.org/feed/gdziadkiewicz/package/nuget/YoloDev.Expecto.TestSdk

**Comment by Alxandr** [comment]
Does this mean that we can re-enable `pack` for PRs? And also; do you need the `_._` file given that you have the props file?

**Comment by Alxandr** [comment]
Ignore that last part about `_._`, I missread. However, I do think I spotted an issue. 
image

As you can see, both are called `expecto.visualstudio.dotnetcore.dll`, which (if memory serves) isn't correct.

**Comment by Alxandr** [comment]
I downloaded the 0.8 version from nuget, and this is how it looks:

image

**Comment by Alxandr** [comment]
And for good measure (while I'm at it); [link to the 0.8 code](https://github.com/YoloDev/YoloDev.Expecto.TestSdk/blob/v0.8.0/src/YoloDev.Expecto.TestSdk/YoloDev.Expecto.TestSdk.fsproj). Also check the bundled `.props` files. There are minor differences between core and non-core.

**Comment by gdziadkiewicz** [comment]
> Does this mean that we can re-enable `pack` for PRs? And also; do you need the `_._` file given that you have the props file?

I will check, I think that we can.

**Comment by gdziadkiewicz** [comment]
I did the changes, let's see the results and do some testing with the package that will be deployed to MyGet. I will later post a link to a test repo utilizing the new version of the package from MyGet.

**Comment by gdziadkiewicz** [comment]
> > Does this mean that we can re-enable `pack` for PRs? And also; do you need the `_._` file given that you have the props file?
> 
> I will check, I think that we can.

This is still not possible - the git-version script seems to not handle PRs well(see the error in https://github.com/YoloDev/YoloDev.Expecto.TestSdk/runs/739288789?check_suite_focus=true#step:9:8 ).

**Comment by Alxandr** [comment]
Yeah. I noticed. I probably have to go over that script (it's been a while). The issue is that it doesn't find where it is in relationship to master.

I'll merge this, we'll see if it get's published to myget, and if it does it would be great if you can test it from there (if it doesn't we'll just have to look at why :P).

Once myget publishing works, adding nuget publishing is pretty straight forward (most of the setup has been done already).

**Comment by gdziadkiewicz** [comment]
@Alxandr I set up my own myget and found out that only the .net core part works when using nugget package. I will convert this PR to draft and try to resolve the problem.

**Comment by Alxandr** [comment]
Let me know if you need any help.

**Comment by gdziadkiewicz** [comment]
I located the problem and will post the details tomorrow. Sent from Mail for Windows 10 From: Aleksander HeintzSent: Saturday, June 6, 2020 19:07To: YoloDev/YoloDev.Expecto.TestSdkCc: Grzegorz Dziadkiewicz; AuthorSubject: Re: [YoloDev/YoloDev.Expecto.TestSdk] Add lib folder dummies for net461to fix pack step errors. (#35) Let me know if you need any help.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by gdziadkiewicz** [comment]
Repo with code showing the problem and logs (acquired by `dotnet test -d test.log`) - https://github.com/gdziadkiewicz/ProblemsWithExpectoTestSdk

Lack of respect for binding redirects in testHost  (app running tests adapters and tests for classic .net framework) causes the Expecto Test Adapter to be loaded correctly only if matching version of FSharp.Core is being used (4.6.*).

Behaviour for matching FSharp.Core version 4.6.2 - https://github.com/gdziadkiewicz/ProblemsWithExpectoTestSdk/blob/master/test.host.20-06-13_02-12-15_03492_1.log#L496-L533
Behaviour for not matching version 4.7.2 - https://github.com/gdziadkiewicz/ProblemsWithExpectoTestSdk/blob/master/test.host.20-06-13_02-12-11_15377_1.log#L310-L398
The app.config used for test runner is fixed and displayed at the start of the log file.

I would like to bind only the classic .net version to FSharp.Core 4.7.0 to make it work for ppl on 4.7.*. Does it make sense for you?

It's worth noticing that this will be also the case for Expecto version when it increases and that .net core is not affected at all, because it does not use app.config for binding redirects.

**Comment by Alxandr** [comment]
Hmm... This seems a bit brittle. My main issue is that we recently downgraded FSharp.Core (another PR, someone wanted to use 4.6). I think this was the main reason why I removed net framework support in the first case 😛. But, supporting some framework configurations is probably better than none - for a while.

I can agree to this fix, but will eventually remove netframework support again. Not sure when, but at some point the cost of supporting it compared to the number of users will make it too burdensome considering this is something I do on the side every now and again.

**Comment by gdziadkiewicz** [comment]
I agree that this will be very brittle for classic .net framework and probably frustrating for the users (who expects the test adapter to stop being detected/working after FSharp.Core or Expecto version upgrade when the bindings redirects are in place?). I even wonder if it makes sense to ship it in that form.

**Comment by gdziadkiewicz** [comment]
I propose to scrap the work and rollback the changes.

**Comment by Alxandr** [comment]
Before we do that; I would like to take a look at the error you're having with binding redirects; cause it's likely quite easily fixable (now that I think about it). We've had the same thing at work, and it's something that could quite easily be fixed by providing some docs.

Could you try adding the following to your test project:

```xml
  <PropertyGroup>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
  </PropertyGroup>
```

**Comment by gdziadkiewicz** [comment]
Did it in https://github.com/gdziadkiewicz/ProblemsWithExpectoTestSdk/commit/c1aa29059df047e5704b5534c41b686d077da3d0 but still got the same result.

**Comment by Alxandr** [comment]
I wonder if it doesn't work in fsproj files 🤔. I will do some investigation.

**Comment by gdziadkiewicz** [comment]
Please share your findings if anything interesting shows up.

**Comment by Alxandr** [comment]
Will do. Once this heat wave pass or I get an AC installed. ATM; just doing my normal 9-5 is hard enough.

**Comment by Alxandr** [comment]
So, I just cloned the repo you linked, and ran the tests (commenting out the failing ones, cause they produce too much noise in the output):

image

As you can see, I do not have any binding errors, but net461 cannot find the test adapter it seems like.

**Comment by Alxandr** [comment]
Oh, wait, no, I'm reading this wrong. It's not the framework that's determining whether or not tests are found, but the fsharp.core version...

**Pull request closed without merging**
